export const BADGES = [
  '@atls/code-service',
  '@atls/schematics',
  '@atls/next-identity-integration',
  '@atls/react-kratos-browser-flows',
  '@atls/nestjs-dataloader',
  '@atls/nestjs-external-renderer',
  '@atls/nestjs-gateway',
  '@atls/nestjs-grpc-errors',
  '@atls/nestjs-grpc-http-proxy',
  '@atls/nestjs-grpc-identity',
  '@atls/nestjs-grpc-playground',
  '@atls/nestjs-grpc-reflection',
  '@atls/nestjs-hydra',
  '@atls/nestjs-keto',
  '@atls/nestjs-kratos',
  '@atls/nestjs-typesense-typeorm',
  '@atls/nestjs-typesense',
  '@atls-ui-generators/button',
  '@atls-ui-generators/input',
  '@atls-ui-generators/icons',
]

export const COLORS = {
  '@atls/nestjs': { labelColor: '#CB5458', color: '#BE4045' },
  '@atls/next': { labelColor: '#354247', color: '#1D282D' },
  '@atls/react': { labelColor: '#43CFF4', color: '#2DBFE6' },
  '@atls-ui': { labelColor: '#097CEB', color: '#0B6DCC' },
  tools: { labelColor: '#ECEEF5', color: '#D7DCEB' },
}
