packageExtensions:
  '@babel/register@*':
    dependencies:
      '@babel/core': '*'
  '@octokit/plugin-paginate-rest@*':
    dependencies:
      '@octokit/core': '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  import-sort-parser-typescript@*:
    dependencies:
      import-sort-parser: '*'
  import-sort-style@*:
    dependencies:
      import-sort-parser: '*'
  ink@*:
    dependencies:
      '@types/yoga-layout': '*'
  jest-resolve@*:
    dependencies:
      jest-haste-map: '*'
  node-fetch@*:
    dependencies:
      encoding: '*'
  webpack-chain@*:
    dependencies:
      tapable: 1.1.3
      webpack: 4.44.2
  webpack@*:
    dependencies:
      json-schema: '*'
  '@jest/test-result@*':
    dependencies:
      jest-haste-map: '*'
      jest-resolve: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - yarn/plugin-essentials/dev.js

yarnPath: yarn.js
