name: Release composite action
description: Create GitHub release for changed packages

inputs:
  GITHUB_TOKEN:
    required: true
    description: GitHub token for creating release

runs:
  using: composite

  steps:
    - name: Create release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspaces changed foreach -v --exclude . release create
