name: Publish composite action

inputs:
  NPM_TOKEN:
    required: true
  WORKSPACE:
    required: false
    default: ''

runs:
  using: composite

  steps:
    - name: List changed workspaces
      if: ${{ inputs.WORKSPACE == '' }}
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspaces changed list

    - name: Show selected workspace
      if: ${{ inputs.WORKSPACE != '' }}
      shell: bash
      run: |
        echo "Selected workspace: ${{ inputs.WORKSPACE }}"

    - name: Verify NPM auth
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn npm whoami --publish
      env:
        YARN_NPM_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
        YARN_NPM_PUBLISH_REGISTRY: https://registry.npmjs.org

    - name: Npm Publish
      if: ${{ inputs.WORKSPACE == '' }}
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspaces changed foreach -vt --no-private npm publish --tolerate-republish --access public
      env:
        YARN_NPM_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
        YARN_NPM_PUBLISH_REGISTRY: https://registry.npmjs.org

    - name: Npm Publish selected workspace
      if: ${{ inputs.WORKSPACE != '' }}
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspace ${{ inputs.WORKSPACE }} npm publish --tolerate-republish --access public
      env:
        YARN_NPM_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
        YARN_NPM_PUBLISH_REGISTRY: https://registry.npmjs.org
