export type { GenerateIconsInput }     from './input.interfaces.js'
export type { GeneratedIconFormatter } from './ports/format.interfaces.js'
export type { GeneratedIconLinter }    from './ports/lint.interfaces.js'
export type { IconModule }             from './ports/output.interfaces.js'
export type { IconOutputReplacer }     from './ports/output.interfaces.js'
export type { IconSource }             from './ports/source.interfaces.js'
export type { IconSourceReader }       from './ports/source.interfaces.js'
export type { IconTransformer }        from './ports/transform.interfaces.js'
export type { TransformIconInput }     from './ports/transform.interfaces.js'
export type { GenerateIconsResult }    from './result.interfaces.js'

export { generateIcons }               from './generate.js'
