name: Checks composite action
description: Run checks

inputs:
  GITHUB_TOKEN:
    required: true
    description: GitHub token
  CHANGED:
    required: false
    description: Run lint and typecheck only for changed files
    default: 'false'

runs:
  using: composite

  steps:
    - name: Checks
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        if [ "${{ inputs.CHANGED }}" = "true" ]; then
          yarn checks run --changed
        else
          yarn checks run
        fi
