name: Checks composite action
description: Run checks

inputs:
  GITHUB_TOKEN:
    required: true
    description: GitHub token

runs:
  using: composite

  steps:
    - name: Checks
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn checks run

    - name: JSR publish dry run
      if: ${{ !cancelled() }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspaces changed foreach -v --no-private bash -c "if [[ -f jsr.json ]]; then dlx jsr publish --dry-run; else echo 'Skipping jsr publish, jsr.json not found'; fi"
