name: Checks composite action
description: Run checks

inputs:
  BASE_REF:
    required: true
    description: Pull request base commit SHA

runs:
  using: composite

  steps:
    - name: Checks
      env:
        RAIJIN_BASE_REF: ${{ inputs.BASE_REF }}
      shell: bash
      run: |
        yarn check --verify --since "$RAIJIN_BASE_REF"
