export { default as typescriptDefaults }        from './defaults.js'
export { applyTypeScriptCompilerOptions }       from './merge/merge.js'
export { resolveTypeScriptCompilerOptions }     from './compiler-options/compiler-options.js'
export { hasTypeScriptProject }                 from './discovery/discover.js'
export { mergeTypeScriptCompilerOptions }       from './merge/merge.js'
export { materializeTypeScriptConfig }          from './materialization/materialize.js'
export { resolveTypeScriptProject }             from './project/project.js'

export type { ResolveTypeScriptCompilerOptionsOptions } from './compiler-options/compiler-options.interfaces.js'
export type { MaterializeTypeScriptConfigOptions } from './materialization/materialize.interfaces.js'
export type { ResolveTypeScriptProjectOptions } from './project/project.interfaces.js'
export type { TypeScriptCompilerOptionsShape }  from './config.interfaces.js'
export type { TypeScriptConfigShape }           from './config.interfaces.js'
export type { TypeScriptProjectConfig }         from './project/project.interfaces.js'
export type { TypeScriptProjectSelection }      from './project/project.interfaces.js'
export type { TypeScriptRuntime }               from './project/project.interfaces.js'
