name: Publish composite action
description: Apply deferred versions for changed packages before publish

inputs:
  GITHUB_TOKEN:
    required: true

runs:
  using: composite

  steps:
    - name: Apply deferred versions
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn release version defer
        yarn release plan create --output .raijin/release-plan.json
        yarn version apply --all
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
