name: Checks

on:
  pull_request:

jobs:
  checks:
    name: Shared checks
    uses: atls/shared/.github/workflows/checks.yaml@master
    permissions: write-all
    with:
      node-version-file: package.json

  raijin:
    name: Raijin checks
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json

      - name: Install
        uses: ./.github/actions/install

      - name: Raijin checks
        shell: bash
        run: |
          yarn raijin:check

  unit:
    name: Unit / windows-latest
    runs-on: windows-latest
    timeout-minutes: 10
    permissions: read-all

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          check-latest: true

      - name: Install
        uses: ./.github/actions/install

      - name: Unit
        shell: bash
        run: yarn test unit
