name: Checks

on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  checks:
    name: Shared checks / Checks
    env:
      NODE_VERSION: '25'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        uses: ./.github/actions/install

      - name: Checks
        uses: ./.github/actions/checks
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGED: 'true'

  raijin:
    name: Raijin checks
    env:
      NODE_VERSION: '25'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: read-all

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        uses: ./.github/actions/install

      - name: Raijin checks
        shell: bash
        run: |
          yarn raijin:check
